spring:
  cloud:
    function:
      definition: normalize
    stream:
      bindings:
        normalize-in-0:
          destination: ${TOPIC_ORDERS_CREATED:dev.orders.created.v1}
        normalize-out-0:
          destination: ${TOPIC_ORDERS_NORMALIZED:dev.orders.normalized.v1}
      binders:
        solace:
          type: solace
          environment:
            solace:
              host: ${tcps://mr-connection-j4qf9k8b3wh.messaging.solace.cloud:55443}
              vpn: ${order-1}
              username: ${solace-cloud-client}
              password: ${t6psp33t2psd3dpfktfe9d6mod}
