spring:
  cloud:
    function:
      definition: normalize

    stream:
      binders:
        solace:
          type: solace
          environment:
            host: ${SOLACE_HOST:mr-connection-j4qf9k8b3wh.messaging.solace.cloud:55443}
            vpn: ${SOLACE_VPN:order-1}
            username: ${SOLACE_USERNAME:solace-cloud-client}
            password: ${SOLACE_PASSWORD:}
            connectRetries: 3
            reconnectRetries: 10

      bindings:
        normalize-in-0:
          destination: ${TOPIC_ORDERS_CREATED:dev/orders/created/v1}
          group: ${QUEUE_ORDERS_NORMALIZER:q.orders.normalizer}
        normalize-out-0:
          destination: ${TOPIC_ORDERS_NORMALIZED:dev/orders/normalized/v1}

      solace:
        bindings:
          normalize-in-0:
            consumer:
              queueAdditionalSubscriptions: ${TOPIC_EVENTS_ERROR:dev/events/error/v1}
          normalize-out-0:
            producer:
              messageProcessorBeanName: solaceMessageProcessor

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always